name: build cms
run-name: ${{ github.actor }} is building cms üöÄ
on:
 pull_request:
    branches:
      - staging
    types:
      - closed
    paths:
      - 'cms/**'        
 workflow_dispatch:
# Some objects are defined but never used lead to warnings when build
# Treating warnings as errors because process.env.CI = true ==> step build cms exit code 1 and fail
# temporary fix by set process.env.CI = false
env:
  CI: false
jobs:
  build-cms:
    runs-on: ubuntu-latest
    if: github.event.action == 'closed' && github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
    steps:
      - run: echo "üéâ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "üêß This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "üîé The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "üí° The ${{ github.repository }} repository has been cloned to the runner."
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'
      - name: Cache node_modules
        uses: actions/cache@v3.0.1
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install dependencies
        run: yarn install --prefer-offline
      - name: Run yarn build-lib
        run: yarn build-lib
      - name: Build cms
        env:
            REACT_APP_LOGIN_URL: ${{ secrets.REACT_APP_LOGIN_URL }}
            REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}
        run: yarn build-cms
      - name: Save cms/build folder
        uses: actions/upload-artifact@v3
        with:
          name: cms-build-folder
          path: cms/build
          retention-days: 1

  deploy-cms:
    runs-on: ubuntu-latest
    needs: build-cms
    steps:
      - name: Download cms/build folder
        uses: actions/download-artifact@v3
        with:
          name: cms-build-folder
          path: cms/build
      - name: Rsync cms/build folder to Server
        uses: easingthemes/ssh-deploy@v2
        env:
            SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            ARGS: ""
            SOURCE: "cms/build"
            REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
            REMOTE_USER: ${{ secrets.REMOTE_USER }}
            TARGET: /home/${{ secrets.REMOTE_USER }}/bworks_2.0/bworks_2.0/cms

  restart-nginx-service:
    needs: build-cms
    runs-on: ubuntu-latest
    steps:
      - name: Restart nginx service
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/${{ secrets.REMOTE_USER }}/bworks_2.0/bworks_2.0/docker-config
            docker-compose -f compose.yaml restart nginx
      - run: echo "üçè This job's status is ${{ job.status }}."
